name: manhunt
version: '${project.version}'
main: org.manhunt.Main
commands:
  sidebar:
  prepare:
  growing:
  team:
  getLastDamageFrom:
  shout:
  setclass:
  getclass:
  randomTeam:
  chat:
  s:
  reset:
